name: Deploy Server
on:
  push:
    branches: main
    paths: 
      - 'server/**'
      - '.github/workflows/deploy-server.yml'
  pull_request:
    branches: main
    paths: 
      - 'server/**'

jobs:
  deploy:
    name: Deploy Server
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/deno
            ~/.deno
          key: ${{ runner.os }}-deno-${{ hashFiles('server/deno.json', 'server/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Cache dependencies
        run: cd server && deno cache --config deno.json main.ts

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "vhybz-server"
          entrypoint: "main.ts"
          root: "server"
          import-map: "deno.json"
        env:
          MONGODB_ATLAS_URI: ${{ secrets.MONGODB_ATLAS_URI }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
