name: Deploy Studio
on:
  push:
    branches: main
    paths: 
      - 'studio/**'
      - '.github/workflows/deploy-studio.yml'
  pull_request:
    branches: main
    paths: 
      - 'studio/**'

jobs:
  deploy:
    name: Deploy Studio
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'studio/package-lock.json'

      - name: Install dependencies
        run: cd studio && npm ci

      - name: Build React Router app
        run: cd studio && npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "vhybz-studio"
          org: "vhybZ"
          entrypoint: "https://deno.land/std@0.208.0/http/file_server.ts"
          root: "studio/build"
