name: Deploy Server
on:
  push:
    branches: main
    paths: 
      - 'server/**'
      - '.github/workflows/deploy-server.yml'
  pull_request:
    branches: main
    paths: 
      - 'server/**'

jobs:
  deploy:
    name: Deploy Server
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: cd server && deno task build
        # Only run if server/deno.json exists and has build task

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "vhybz-server"
          org: "vhybZ"
          entrypoint: "main.ts"
          root: "server"
          env: |
            MONGODB_ATLAS_URI=${{ secrets.MONGODB_ATLAS_URI }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
